// <auto-generated />
using System;
using FurniComply.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurniComply.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216200753_AddCorrectiveActions")]
    partial class AddCorrectiveActions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurniComply.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Action = "Marked Non-Compliant",
                            Actor = "Safety Officer",
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6283),
                            Details = "Issue logged and corrective action requested.",
                            EntityId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            EntityName = "ComplianceCheck",
                            TimestampUtc = new DateTime(2026, 2, 1, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplianceAlertRuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("TriggeredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceAlertRuleId");

                    b.ToTable("ComplianceAlerts");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceAlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("ThresholdValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleKey")
                        .IsUnique();

                    b.ToTable("ComplianceAlertRules");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComplianceCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abababab-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Safety",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("abababab-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Quality",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("abababab-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "Supplier",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("abababab-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Regulatory",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ComplianceCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplianceStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RiskLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceCategoryId");

                    b.HasIndex("ComplianceStatusId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RiskLevelId");

                    b.ToTable("ComplianceChecks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CheckedAtUtc = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceCategoryId = new Guid("abababab-2222-2222-2222-222222222222"),
                            ComplianceStatusId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6251),
                            Notes = "Supplier material certification verified.",
                            PolicyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RiskLevelId = new Guid("cdcdcdcd-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CheckedAtUtc = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceCategoryId = new Guid("abababab-1111-1111-1111-111111111111"),
                            ComplianceStatusId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6255),
                            Notes = "Safety signage missing in finishing bay.",
                            PolicyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RiskLevelId = new Guid("cdcdcdcd-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceStatusMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComplianceStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Pending",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Compliant",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Non-Compliant",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.CorrectiveAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid>("ComplianceCheckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EvidenceSubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceCheckId", "Status");

                    b.HasIndex("Status", "DueAtUtc");

                    b.ToTable("CorrectiveActions");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PolicyCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PolicyCategoryId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "QMS-001",
                            Content = "Defines minimum quality criteria for raw materials.",
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6130),
                            EffectiveDateUtc = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Owner = "Quality Manager",
                            PolicyCategoryId = new Guid("ffffffff-2222-2222-2222-222222222222"),
                            Status = 1,
                            Title = "Material Quality Standard",
                            Version = "1.2"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "SAFE-010",
                            Content = "Defines safety practices for production areas.",
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6139),
                            EffectiveDateUtc = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Owner = "Safety Officer",
                            PolicyCategoryId = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            Status = 1,
                            Title = "Workshop Safety Standard",
                            Version = "2.0"
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.PolicyCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolicyCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Safety",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("ffffffff-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Quality",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("ffffffff-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "Procurement",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("ffffffff-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Environmental",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.PolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyVersions");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcurementOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualityStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementOrderId");

                    b.ToTable("ProcurementItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6221),
                            ItemName = "Premium Oak Planks",
                            Notes = "Moisture content under 8%.",
                            ProcurementOrderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            QualityStandard = "QMS-001",
                            Quantity = 120,
                            UnitCost = 95m
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6227),
                            ItemName = "Protective Finish",
                            Notes = "VOC compliant finish.",
                            ProcurementOrderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            QualityStandard = "SAFE-010",
                            Quantity = 60,
                            UnitCost = 35m
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6229),
                            ItemName = "Steel Brackets",
                            Notes = "Batch to be inspected on arrival.",
                            ProcurementOrderId = new Guid("66666666-6666-6666-6666-666666666666"),
                            QualityStandard = "QMS-001",
                            Quantity = 450,
                            UnitCost = 12m
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProcurementStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementStatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProcurementOrders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6195),
                            OrderDateUtc = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "PO-2026-0001",
                            ProcurementStatusId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SupplierId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TotalAmount = 18500m
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6202),
                            OrderDateUtc = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderNumber = "PO-2026-0002",
                            ProcurementStatusId = new Guid("99999999-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SupplierId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TotalAmount = 9400m
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementStatusMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProcurementStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Draft",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Approved",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            IsActive = true,
                            Name = "Ordered",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            IsActive = true,
                            Name = "Received",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            IsActive = true,
                            Name = "Closed",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("dddddddd-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsActive = true,
                            Name = "Cancelled",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.RegulatoryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReportStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportStatusId");

                    b.ToTable("RegulatoryReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6300),
                            PeriodEndUtc = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodStartUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReportStatusId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ReportType = "Monthly Safety Summary",
                            SubmittedAtUtc = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "January safety report submitted to regulator."
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ReportStatusMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReportStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Draft",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Submitted",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Accepted",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("77777777-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IsActive = true,
                            Name = "Rejected",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.RiskLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskLevels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdcdcdcd-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Low",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("cdcdcdcd-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Medium",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("cdcdcdcd-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "High",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("cdcdcdcd-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Critical",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReviewUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("RenewalDueUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCategoryId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ApprovalStatus = 0,
                            Certifications = "FSC, ISO 9001",
                            ContactEmail = "qa@oakline.example",
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6162),
                            Name = "Oakline Timber Co.",
                            Rating = 4.6m,
                            Status = 0,
                            SupplierCategoryId = new Guid("eeeeeeee-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ApprovalStatus = 0,
                            Certifications = "ISO 14001",
                            ContactEmail = "quality@precision.example",
                            CreatedAtUtc = new DateTime(2026, 2, 16, 20, 7, 53, 474, DateTimeKind.Utc).AddTicks(6169),
                            Name = "Precision Hardware Ltd.",
                            Rating = 3.2m,
                            Status = 1,
                            SupplierCategoryId = new Guid("eeeeeeee-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.SupplierCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SupplierCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Raw Materials",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Hardware",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "Finishing",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Packaging",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.SupplierComplianceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentStatus")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ExpiryDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierComplianceDocuments");
                });

            modelBuilder.Entity("FurniComply.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceAlert", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ComplianceAlertRule", "ComplianceAlertRule")
                        .WithMany()
                        .HasForeignKey("ComplianceAlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceAlertRule");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ComplianceCheck", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ComplianceCategory", "ComplianceCategory")
                        .WithMany()
                        .HasForeignKey("ComplianceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniComply.Domain.Entities.ComplianceStatusMaster", "ComplianceStatus")
                        .WithMany()
                        .HasForeignKey("ComplianceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniComply.Domain.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniComply.Domain.Entities.RiskLevel", "RiskLevel")
                        .WithMany()
                        .HasForeignKey("RiskLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceCategory");

                    b.Navigation("ComplianceStatus");

                    b.Navigation("Policy");

                    b.Navigation("RiskLevel");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.CorrectiveAction", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ComplianceCheck", "ComplianceCheck")
                        .WithMany()
                        .HasForeignKey("ComplianceCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplianceCheck");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Policy", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.PolicyCategory", "PolicyCategory")
                        .WithMany()
                        .HasForeignKey("PolicyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyCategory");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.PolicyVersion", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.Policy", "Policy")
                        .WithMany("PolicyVersions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementItem", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ProcurementOrder", "ProcurementOrder")
                        .WithMany("Items")
                        .HasForeignKey("ProcurementOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementOrder");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementOrder", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ProcurementStatusMaster", "ProcurementStatus")
                        .WithMany()
                        .HasForeignKey("ProcurementStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniComply.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementStatus");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.RegulatoryReport", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.ReportStatusMaster", "ReportStatus")
                        .WithMany()
                        .HasForeignKey("ReportStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportStatus");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Supplier", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.SupplierCategory", "SupplierCategory")
                        .WithMany()
                        .HasForeignKey("SupplierCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplierCategory");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.SupplierComplianceDocument", b =>
                {
                    b.HasOne("FurniComply.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ComplianceDocuments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FurniComply.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FurniComply.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FurniComply.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FurniComply.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Policy", b =>
                {
                    b.Navigation("PolicyVersions");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.ProcurementOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FurniComply.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ComplianceDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
